# Generated by Django 2.1.2 on 2018-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0003_auto_20181103_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
