# Generated by Django 2.1.2 on 2018-11-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0004_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
